/*
 * Gravitee.io APIM - Management API - Environments
 * This is the OpenAPI specification for our new version of APIM Management API.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: team-apim@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kafbat.ui.model.gravitee;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


@JsonPropertyOrder({
  ClustersResponse.JSON_PROPERTY_DATA,
  ClustersResponse.JSON_PROPERTY_PAGINATION,
  ClustersResponse.JSON_PROPERTY_LINKS
})
public class ClustersResponse {
  public static final String JSON_PROPERTY_DATA = "data";
  @jakarta.annotation.Nullable
  private List<@Valid Cluster> data = new ArrayList<>();

  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @jakarta.annotation.Nullable
  private Pagination pagination;

  public static final String JSON_PROPERTY_LINKS = "links";
  @jakarta.annotation.Nullable
  private Links links;

  public ClustersResponse() {
  }

  public ClustersResponse data(@jakarta.annotation.Nullable List<@Valid Cluster> data) {
    this.data = data;
    return this;
  }

  public ClustersResponse addDataItem(Cluster dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Valid Cluster> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@jakarta.annotation.Nullable List<@Valid Cluster> data) {
    this.data = data;
  }


  public ClustersResponse pagination(@jakarta.annotation.Nullable Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_PAGINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Pagination getPagination() {
    return pagination;
  }


  @JsonProperty(JSON_PROPERTY_PAGINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@jakarta.annotation.Nullable Pagination pagination) {
    this.pagination = pagination;
  }


  public ClustersResponse links(@jakarta.annotation.Nullable Links links) {
    this.links = links;
    return this;
  }

  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Links getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@jakarta.annotation.Nullable Links links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClustersResponse clustersResponse = (ClustersResponse) o;
    return Objects.equals(this.data, clustersResponse.data)
        && Objects.equals(this.pagination, clustersResponse.pagination)
        && Objects.equals(this.links, clustersResponse.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, pagination, links);
  }

  @Override
  public String toString() {
    return "class ClustersResponse {\n"
        + "    data: " + toIndentedString(data) + "\n"
        + "    pagination: " + toIndentedString(pagination) + "\n"
        + "    links: " + toIndentedString(links) + "\n"
        + "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

