/*
 * Gravitee.io APIM - Management API - UI
 * This is the OpenAPI specification for our new version of APIM Management API.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: team-apim@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kafbat.ui.model.gravitee;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;


/**
 * List of links for pagination
 */
@JsonPropertyOrder({
  Links.JSON_PROPERTY_SELF,
  Links.JSON_PROPERTY_FIRST,
  Links.JSON_PROPERTY_LAST,
  Links.JSON_PROPERTY_PREVIOUS,
  Links.JSON_PROPERTY_NEXT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-08T11:57:00.726865+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class Links {
  public static final String JSON_PROPERTY_SELF = "self";
  @jakarta.annotation.Nullable
  private String self;

  public static final String JSON_PROPERTY_FIRST = "first";
  @jakarta.annotation.Nullable
  private String first;

  public static final String JSON_PROPERTY_LAST = "last";
  @jakarta.annotation.Nullable
  private String last;

  public static final String JSON_PROPERTY_PREVIOUS = "previous";
  @jakarta.annotation.Nullable
  private String previous;

  public static final String JSON_PROPERTY_NEXT = "next";
  @jakarta.annotation.Nullable
  private String next;

  public Links() {
  }

  public Links self(@jakarta.annotation.Nullable String self) {
    this.self = self;
    return this;
  }

  /**
   * Link to current resource
   * @return self
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelf() {
    return self;
  }


  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelf(@jakarta.annotation.Nullable String self) {
    this.self = self;
  }


  public Links first(@jakarta.annotation.Nullable String first) {
    this.first = first;
    return this;
  }

  /**
   * In a paginated response, link to the first page
   * @return first
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_FIRST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirst() {
    return first;
  }


  @JsonProperty(JSON_PROPERTY_FIRST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirst(@jakarta.annotation.Nullable String first) {
    this.first = first;
  }


  public Links last(@jakarta.annotation.Nullable String last) {
    this.last = last;
    return this;
  }

  /**
   * In a paginated response, link to the last page
   * @return last
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_LAST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLast() {
    return last;
  }


  @JsonProperty(JSON_PROPERTY_LAST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLast(@jakarta.annotation.Nullable String last) {
    this.last = last;
  }


  public Links previous(@jakarta.annotation.Nullable String previous) {
    this.previous = previous;
    return this;
  }

  /**
   * In a paginated response, link to the previous page. Maybe null if current is the first page
   * @return previous
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PREVIOUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrevious() {
    return previous;
  }


  @JsonProperty(JSON_PROPERTY_PREVIOUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrevious(@jakarta.annotation.Nullable String previous) {
    this.previous = previous;
  }


  public Links next(@jakarta.annotation.Nullable String next) {
    this.next = next;
    return this;
  }

  /**
   * In a paginated response, link to the next page. Maybe null if current is the last page
   * @return next
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_NEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNext() {
    return next;
  }


  @JsonProperty(JSON_PROPERTY_NEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNext(@jakarta.annotation.Nullable String next) {
    this.next = next;
  }


  /**
   * Return true if this Links object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Links links = (Links) o;
    return Objects.equals(this.self, links.self) &&
        Objects.equals(this.first, links.first) &&
        Objects.equals(this.last, links.last) &&
        Objects.equals(this.previous, links.previous) &&
        Objects.equals(this.next, links.next);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, first, last, previous, next);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Links {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

